CREATE TABLE reminder_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

INSERT INTO reminder_lists (name, created_at)
VALUES ('Reminders', CURRENT_TIMESTAMP);

ALTER TABLE reminders
ADD COLUMN list_id BIGINT;

UPDATE reminders
SET list_id = (
    SELECT id
    FROM reminder_lists
    WHERE name = 'Reminders'
);

ALTER TABLE reminders
ADD CONSTRAINT fk_reminders_list
FOREIGN KEY (list_id)
REFERENCES reminder_lists (id);

ALTER TABLE reminders
ALTER COLUMN list_id SET NOT NULL;
