spring:
  application:
    name: reminder-api
  datasource:
    url: jdbc:postgresql://localhost:5432/reminder_app
    username: zhangzhengyang
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
